### ISSUE TITLE
Negative Longitude/latitude not handled (502 response)

### ISSUE THREAD

**Issue by rosario-raulin** [CodeForMD/magdego-server#13]
http://api.magdego.de/departure-time/location/-0.133700/51.509980 produces a 502 (internal server error). However, negative longitudes/latitudes are possible.

**Comment by rosario-raulin** [comment]
http://api.magdego.de/departure-time/location/0.133700/51.509980 produces a 502 as well.

**Comment by filter1** [comment]
Fixed.
