### ISSUE TITLE
Shows only loading screen when no Journeys are available. 

### ISSUE THREAD

**Issue by Moezalez** [CodeForMD/magdego-server#17]

**Comment by filter1** [comment]
Yeah, there is a problem with the API. If the API returns [], everything will be fine (redirect to /demo). I somehow fucked it up and in some situations it's returning [[]].

For instance:
http://api.magdego.de/departure-time/location/-73.984638/40.759211

returns [[]]

This has to to with the callback value. Check Line 73 in departure.js

**Comment by Moezalez** [comment]
The async.map (Line 190) maps the array of l.73 into another array.
